server.port: 7003
logging:
  level:
    root: INFO
    se.magnus: DEBUG
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: password
    hikari:
      initialization-fail-timeout: 60000
  application:
    name: review

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---

spring.profiles: docker

spring:
  datasource:
    url: jdbc:mysql://mysql/review-db
    
server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/